# Generated by Django 6.0 on 2026-01-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babytracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyinfo',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Enter height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='babyinfo',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Enter weight in kg', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='babyinfo',
            name='name',
            field=models.CharField(default='My baby', max_length=50),
        ),
    ]
