# Generated by Django 6.0 on 2026-01-05 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babytracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('head_circumference_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babytracker.babyinfo')),
            ],
        ),
    ]
